const data = {
  products: [
    {
      name: "Free Shirt",
      slug: "free shirt",
      category: "shirts",
      image: "/images/shirt1.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Free Shirt",
      slug: "free shirt",
      category: "shirts",
      image: "/images/shirt2.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Free Shirt",
      slug: "free shirt",
      category: "shirts",
      image: "/images/shirt3.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Free Pant",
      slug: "free Pant",
      category: "pants",
      image: "/images/pants1.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: "A popular pant",
    },
    {
      name: "Free Pant",
      slug: "free Pant",
      category: "pants",
      image: "/images/pants2.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: "A popular pant",
    },
    {
      name: "Free Pant",
      slug: "free Pant",
      category: "paints",
      image: "/images/pants3.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: "A popular pant",
    },
  ],
};
export default data;
